#lang scheme
(define size 2)
(define pi 3.14159)
(define radius 10)
(* pi (* radius radius))
(define circumference (* 2 pi radius))
(define (square x) (* x x))
(square 41)
(define (sum-of-squares x y)
  (+ (square x) (square y)))

(sum-of-squares 3 4)
(define (abs x)
  (cond ((> x 0) x)
        ((= x 0) 0)
        ((< x 0) (-x))))
(define (abs2 x)
  (cond ((< x 0) (-x))
        (else x)))
(define (abs3 x)
  (if (< x 0)
      (-x)
      x))
(define (>= x y)
  (not (< x y)))

